# Generated by Django 4.0.6 on 2023-01-04 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('orderId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('orderData', models.TextField()),
                ('totalAmount', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('Conform', 'Conform')], default='pending', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
