# Generated by Django 4.0.6 on 2023-01-04 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_ordertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('subCategoryName', models.CharField(max_length=100)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.FloatField()),
                ('productDescription', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('productImage', models.CharField(max_length=100)),
                ('productImage1', models.CharField(max_length=100)),
                ('productImage2', models.CharField(max_length=100)),
                ('productImage3', models.CharField(max_length=100)),
                ('productImage4', models.CharField(max_length=100)),
                ('productImage5', models.CharField(max_length=100)),
                ('subCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.subcategory')),
            ],
        ),
    ]
