# Generated by Django 4.0.6 on 2023-01-05 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('AddToCartId', models.AutoField(primary_key=True, serialize=False)),
                ('AddToCartData', models.TextField()),
                ('status', models.CharField(max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
