# Generated by Django 4.0.6 on 2023-01-05 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_addtocart'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingAndReview',
            fields=[
                ('ratingId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=1000)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ordertable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
