# Generated by Django 4.0.6 on 2023-01-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_ratingandreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingandreview',
            name='rating',
            field=models.FloatField(),
        ),
    ]
