# Generated by Django 4.0.6 on 2023-01-10 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_productdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='profileId',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='wishlist',
            new_name='wishlistId',
        ),
    ]
