# Generated by Django 4.0.6 on 2023-01-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_todaydeals'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='TodayDeals',
            field=models.BooleanField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='frequentlyPurchase',
            field=models.BooleanField(default='1'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TodayDeals',
        ),
    ]
