# Generated by Django 4.0.6 on 2023-01-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_product_todaydeals_product_frequentlypurchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='BestSeller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='TopRate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='TodayDeals',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='frequentlyPurchase',
            field=models.BooleanField(default=False),
        ),
    ]
